name: Publish to PyPI

on:
    push:
        paths:
            - 'ure/__version__.py'
        branches:
            - main

permissions:
    contents: write
    deployments: write

jobs:
    main:
        name: Publish artifacts
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ure
        permissions:
            id-token: write
            contents: write
            deployments: write
        steps:
            -   uses: actions/checkout@v3

            # -   name: Set up latest Python
            #     uses: actions/setup-python@v4
            #     with:
            #         python-version: '3.10'

            -   name: Install Hatch
                uses: pypa/hatch@install
            
        
            -   name: build package
                run: hatch build
            
                
            -   name: Create github tag
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    VERSION=$(hatch version)
                    git config user.name github-actions
                    git config user.email github-actions@github.com
                    git tag -a "v$VERSION" -m "release new v$VERSION version"
                    git push origin --tags
            
            -   name: Publish package distributions to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
    
